# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image backend
      inputs:
        containerRegistry: 'azure_dp'
        repository: 'frontendandbackend'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: Build an image frontend
      inputs:
        containerRegistry: 'azure_dp'
        repository: 'frontendandbackend'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Push container image to Azure Container Registry
      inputs:
        containerRegistry: 'azure_dp'
        repository: 'frontendandbackend'
        command: 'push'
        tags: |
          $(Build.BuildId)
          latest